version: '3.5'

networks: 
    quranapp:
        driver: 'bridge'

services: 
    nginx:
        image: nginx:alpine
        container_name: "${CONTAINER_PREFIX}_nginx"
        restart: 'unless-stopped'
        tty: true
        ports:
            - "${NGINX_PORT}:8000"
        volumes: 
            - './src:/var/www/app'
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - '${PWD}/docker/dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
        depends_on: 
            - 'php'
            - 'postgres'
        networks: 
            - 'quranapp'

    postgres:
        image: 'postgres:14.4-alpine'
        container_name: "${CONTAINER_PREFIX}_postgres"
        restart: 'unless-stopped'
        tty: true
        ports:
            - "5433:5432"
        volumes:
            - '${PWD}/docker/dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
            - './postgresql:/var/lib/postgresql/data'
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            QURANAPP_USER: 'quranapp'
            QURANAPP_PW: 'quranapp'
        networks:
            - 'quranapp'

    php:
        build:
            context: '.'
            dockerfile: '${PWD}/Dockerfile'
        image: '${CONTAINER_PREFIX}:latest'
        container_name: "${CONTAINER_PREFIX}_php"
        restart: 'unless-stopped'
        tty: true
        working_dir: '/var/www/app'
        volumes: 
            - './src:/var/www/app'
            - '${PWD}/docker/dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
        ports: 
            - "${PHP_PORT}:9000"
        networks: 
            - 'quranapp'

    redis:
        image: 'redis:alpine'
        container_name: "${CONTAINER_PREFIX}_redis"
        ports:
            - "${REDIS_PORT}:6378"
        networks:
            - 'quranapp'